language: python

python:
    - "3.6"

before_install:
    - sudo apt-get update
    - sudo apt-get -y install python-pip
    - sudo pip install --upgrade pip
    - pip install --upgrade pip
    - pip install pep8
    - pip install autopep8

script:
    # Run pep8 on all .py files in all subfolders
    # (I ignore "E402: module level import not at top of file"
    # because of use case sys.path.append('..'); import <module>)
    - find . -name \*.py -exec pep8 --ignore=E402 {} +

notifications:
  webhooks:
    urls:
      - https://discordapp.com/api/webhooks/323265936360734722/9RMi6gXaqwIzDE1wj05o7wiT0KmEbnsuolDTakYT1rhLdNHSQjoKLpUGMO_kYDL_WdbX
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
